language: go
go:
  - '1.8'
branches:
  only:
    - '/^v[0-9]/'
install: true
script:
  - ./go.test.sh
after_success:
  - npm run coverage
  - 'npm run mocha:json'
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'bash <(curl -s https://codecov.octoblu.com/bash)'
notifications:
  webhooks:
    - 'https://beekeeper.octoblu.com/webhooks/travis:ci'
